import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import SidebarComponent from '@/components/sidebar/sidebar-component';
import Header from '@/components/header/header';
import AuthProvider from '../providers/AuthProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session?: import('next-auth').Session | null;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex h-screen overflow-hidden antialiased`}
      >
        <AuthProvider>
          <SidebarComponent />
          <div className="flex h-full flex-1 flex-col">
            <Header />
            <main className="flex-1 overflow-y-auto md:p-1">{children}</main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
